"""Curated illustration subjects: (subject, what to draw, short noun, keywords, weight).

Weights are measured units/design for that theme in the seller's catalogue
where the theme exists; 1.0 where it is a new niche.
"""
S = [
# --- motorcycling: the strongest measured theme (biker 4.00, motorcycle 4.36)
("Biker","a chopper motorcycle in three-quarter view, long forks, ape hangers","MOTORBIKE","Motorcycle Chopper Cafe Racer Rider",4.00),
("Cafe Racer","a cafe racer motorcycle in side profile, clip-on bars, bum-stop seat","CAFE RACER","Biker Motorbike Retro Ton Up",4.00),
("Superbike","a sports motorcycle leaned into a corner, knee down","SUPERBIKE","Moto GP Track Day Racer Rider",4.36),
("Motocross","a motocross bike mid-jump, rider standing on the pegs","MOTOCROSS BIKE","MX Enduro Dirt Bike Scrambler",1.60),
("Scooter","a classic Italian scooter with chrome mirrors","SCOOTER","Mod Vespa Lambretta Scooter Club",2.00),
("Trike","a three-wheeled motorcycle trike","TRIKE","Biker Trike Custom Motorbike",1.50),
("Touring Bike","a loaded touring motorcycle with panniers","TOURING BIKE","Tourer Biker Long Distance Rider",1.50),
# --- vehicles
("Off Roading","a boxy 4x4 climbing a rocky incline, articulated suspension","4X4","Off Road Green Laning Land Rover",2.00),
("Classic Car","a 1960s British sports car in side profile","CLASSIC CAR","Classic Motoring Retro Car Show",1.60),
("Hot Rod","a chopped hot rod with exposed engine and flames","HOT ROD","Rat Rod Custom Kustom Drag",1.60),
("Rally","a rally car sliding on gravel, mud spray","RALLY CAR","Rallying Stage Rally Co Driver",1.40),
("Drifting","a drift car in oversteer with tyre smoke","DRIFT CAR","Drift Track Day JDM Tuner",1.40),
("Trucker","an articulated lorry cab in three-quarter view, chrome stacks","LORRY","Lorry Driver HGV Trucking Haulage",1.64),
("Camper Van","a classic split-screen camper van, surfboard on the roof","CAMPER VAN","Campervan Van Life Road Trip",1.30),
("Caravanning","a retro touring caravan with an awning","CARAVAN","Caravan Club Touring Camp Site",1.30),
("Tractor","a vintage tractor in side profile, large rear tyres","TRACTOR","Farmer Farming Agriculture Field",2.10),
("Steam Train","a steam locomotive at speed with a plume","STEAM TRAIN","Railway Trainspotting Heritage Line",1.30),
("Narrowboat","a narrowboat at a canal lock","NARROWBOAT","Canal Barge Waterways Boating",0.90),
("Aviation","a Spitfire banking against cloud","SPITFIRE","RAF Warbird Aircraft Flying",1.60),
("Sailing","a yacht heeling hard with spray","SAILING BOAT","Sailor Yacht Regatta Crew",1.00),
# --- music
("Guitar","an electric guitar at a three-quarter angle","GUITAR","Guitarist Electric Bass Strings Riff",2.30),
("Acoustic Guitar","an acoustic guitar with open sound hole detail","ACOUSTIC GUITAR","Singer Songwriter Folk Strings",2.00),
("Drumming","a full drum kit seen from the drummer's side","DRUM KIT","Drummer Sticks Snare Cymbals",2.00),
("Bass","a bass guitar in side profile","BASS GUITAR","Bassist Four String Groove Low End",2.00),
("Vinyl","a record spinning on a turntable with the arm down","TURNTABLE","Vinyl Records Crate Digging DJ",1.80),
("Saxophone","a saxophone at a three-quarter angle","SAXOPHONE","Sax Jazz Brass Player Horn",1.40),
("Piano","grand piano keys in dramatic perspective","PIANO","Pianist Keys Keyboard Player",1.20),
("Live Music","a stack of amplifiers and a microphone stand","AMP STACK","Gig Band Live Stage Rock",1.80),
# --- fishing & field
("Fishing","a bent fishing rod with a carp breaking the surface","FISHING ROD","Angler Carp Coarse Tackle Bailiff",1.50),
("Fly Fishing","a fly reel and a leaping trout","FLY ROD","Fly Fishing Trout Salmon River",1.40),
("Sea Fishing","a beachcaster rod against breaking surf","BEACHCASTER","Sea Angler Cod Bass Shore",1.30),
("Shooting","a break-action shotgun and a clay","SHOTGUN","Clay Pigeon Game Shooting Field",1.10),
("Archery","a recurve bow drawn with an arrow nocked","BOW","Archer Target Field Archery",1.20),
("Bird Watching","binoculars with a kingfisher perched beyond","BINOCULARS","Birder Twitcher RSPB Ornithology",0.90),
("Metal Detecting","a metal detector coil over ground with a coin","METAL DETECTOR","Detectorist Treasure Hoard Finds",1.00),
("Bee Keeping","a beehive with bees in flight","BEEHIVE","Beekeeper Apiary Honey Hive",0.90),
("Gardening","a spade, fork and watering can arranged","GARDEN SPADE","Gardener Allotment Grow Your Own",1.00),
("Allotment","a wheelbarrow heaped with vegetables","ALLOTMENT","Veg Plot Grow Your Own Digging",0.90),
# --- sport & fitness
("Gym","a loaded barbell mid-deadlift","BARBELL","Weightlifting Powerlifting Training",2.55),
("Boxing","a pair of laced boxing gloves hanging","BOXING GLOVES","Boxer Ring Sparring Fight Night",1.30),
("MMA","a pair of grappling gloves and a cage panel","MMA GLOVES","Mixed Martial Arts Cage UFC",1.60),
("Muay Thai","a fighter throwing a knee, Thai shorts","MUAY THAI","Thai Boxing Clinch Eight Limbs",1.60),
("Rugby","a rugby ball and posts beyond","RUGBY BALL","Rugby Union League Scrum Forward",1.20),
("Cricket","a cricket bat, ball and stumps","CRICKET BAT","Cricketer Batsman Bowler Wicket",0.90),
("Football","a football and worn goal net","FOOTBALL","Sunday League Striker Soccer",0.74),
("Golf","a driver mid-swing with a ball on a tee","GOLF CLUB","Golfer Handicap Fairway Bogey",1.20),
("Darts","three darts in the treble twenty","SET OF DARTS","Oche Checkout Arrows Pub League",1.20),
("Snooker","a cue striking the cue ball, pocket beyond","SNOOKER CUE","Pool Billiards Break Century",1.00),
("Cycling","a road bicycle in side profile, drop bars","BICYCLE","Cyclist Road Bike Peloton Climb",1.40),
("Mountain Biking","a mountain bike airborne off a berm","MOUNTAIN BIKE","MTB Trail Downhill Enduro",1.40),
("Running","a pair of worn running shoes","RUNNING SHOES","Runner Marathon Parkrun 10k",1.20),
("Swimming","a pair of goggles and a lane rope","GOGGLES","Swimmer Front Crawl Lengths Pool",0.90),
("Rowing","a single scull with oars mid-stroke","ROWING BOAT","Rower Regatta Crew Erg",0.90),
("Climbing","a carabiner, rope and chalk bag","CLIMBING ROPE","Climber Bouldering Crag Belay",0.90),
("Surfing","a surfboard against a breaking wave","SURFBOARD","Surfer Line Up Barrel Swell",1.00),
("Skiing","crossed skis and poles in snow","SKIS","Skier Piste Alpine Off Piste",1.00),
("Snowboarding","a snowboard mid-grab against sky","SNOWBOARD","Snowboarder Powder Park Rail",1.00),
("Kayaking","a kayak punching through white water","KAYAK","Canoe Paddle White Water River",0.90),
("Scuba Diving","a diving mask, regulator and bubbles","DIVE GEAR","Diver Wreck Reef Open Water",1.40),
("Horse Riding","a horse's head in profile with bridle","HORSE","Equestrian Dressage Stables Pony",1.10),
("Motorsport","a chequered flag and a racing helmet","RACING HELMET","Motorsport Circuit Grid Lap",1.40),
# --- trades
("Welding","a welding mask with a spray of sparks","WELDING TORCH","Welder Fabricator MIG TIG Sparks",1.10),
("Carpentry","a hand plane and chisel on timber","CHISEL","Carpenter Joiner Woodwork Sawdust",1.10),
("Plumbing","a pipe wrench and copper elbow","PIPE WRENCH","Plumber Heating Engineer Gas Safe",1.10),
("Electrician","a pair of side cutters and cable","SIDE CUTTERS","Sparky Electrician Wiring Consumer Unit",1.10),
("Mechanic","a socket set and a spanner","SPANNER","Mechanic Garage Workshop Grease",1.30),
("Builder","a trowel and a run of brickwork","TROWEL","Bricklayer Builder Site Hod",1.10),
("Farming","a combine harvester in a field","COMBINE","Farmer Harvest Arable Agriculture",2.10),
("Chef","a chef's knife and board","CHEF KNIFE","Chef Kitchen Brigade Service",1.10),
("Baking","a stand mixer and rolling pin","ROLLING PIN","Baker Sourdough Pastry Proving",0.90),
("Barbecue","a kettle barbecue with rising flame","BARBECUE","BBQ Smoker Low And Slow Grill",1.00),
("Home Brewing","a pint glass, hops and hydrometer","BREW KIT","Homebrew Real Ale CAMRA Cask",1.00),
("Photography","a DSLR with a long lens","CAMERA","Photographer Lens Aperture Shutter",1.20),
("Drone Flying","a quadcopter drone in flight","DRONE","Drone Pilot FPV Aerial Quadcopter",0.90),
("Model Railway","a model locomotive on scale track","MODEL RAILWAY","OO Gauge Modeller Layout Trainset",0.90),
("Chess","a knight piece on a board","CHESS BOARD","Chess Gambit Endgame Grandmaster",0.90),
# --- animals: measured eagle 6.02, stag 5.13, tiger 3.86, lion 2.78
("Eagle","an eagle with wings spread, talons forward","EAGLE","Eagle Bird Of Prey Wings Raptor",6.02),
("Stag","a stag's head with full antlers","STAG","Stag Deer Antlers Highland Monarch",5.13),
("Tiger","a tiger's head facing forward, intense","TIGER","Tiger Big Cat Stripes Wild",3.86),
("Lion","a lion's head with full mane","LION","Lion Big Cat Mane King Pride",2.78),
("Wolf","a howling wolf against a moon","WOLF","Wolf Pack Howl Lone Wild",1.10),
("Gorilla","a silverback gorilla's head","GORILLA","Gorilla Silverback Ape Primate",2.45),
("Bear","a grizzly bear's head roaring","BEAR","Bear Grizzly Wild Woodland",1.20),
("Highland Cow","a highland cow's shaggy head","HIGHLAND COW","Highland Cow Coo Scottish Cattle",1.00),
("Octopus","an octopus with curling tentacles","OCTOPUS","Octopus Kraken Tentacles Deep Sea",0.70),
("Shark","a great white shark rising","SHARK","Shark Great White Jaws Ocean",1.20),
("Owl","an owl's face, large eyes","OWL","Owl Barn Owl Nocturnal Bird",1.10),
("Fox","a fox's head in profile","FOX","Fox Vixen Countryside Wildlife",1.00),
("Horse","a galloping horse, mane flying","HORSE","Horse Equine Gallop Stallion",1.10),
("Dog","a dog's head, alert ears","DOG","Dog Lover Puppy Best Friend",1.00),
("Cat","a cat's face, half-lidded eyes","CAT","Cat Lover Kitten Feline Moggy",1.00),
("Dragon","a coiled dragon breathing fire","DRAGON","Dragon Wyvern Fantasy Fire",1.10),
("Skull","a detailed human skull, three-quarter","SKULL","Skull Gothic Tattoo Biker Death",1.84),
# --- forces & flags
("Army","a pair of crossed rifles and a beret","RIFLES","Army Infantry Regiment Veteran",1.40),
("Royal Navy","an anchor with rope","ANCHOR","Navy Sailor Ship Matelot",1.30),
("RAF","a roundel and a jet silhouette","ROUNDEL","RAF Aircrew Squadron Flying",1.40),
("Royal Marines","a commando dagger","DAGGER","Marines Commando Bootneck Green Beret",1.20),
("Veteran","a poppy and a set of medals","MEDALS","Veteran Remembrance Poppy Service",1.30),
]
